/**:
  ros__parameters:
    frame:
      base_frame: "base_link"
      ndt_base_frame: "ndt_base_link"
      map_frame: "map"

    sensor_points:
      timeout_sec: 1.0
      required_distance: 10.0

    ndt:
      trans_epsilon: 0.01
      step_size: 0.1
      resolution: 2.0
      max_iterations: 30
      num_threads: 4

    initial_pose_estimation:
      particles_num: 200
      n_startup_trials: 100

    validation:
      initial_pose_timeout_sec: 1.0
      initial_pose_distance_tolerance_m: 10.0
      initial_to_result_distance_tolerance_m: 3.0
      critical_upper_bound_exe_time_ms: 100.0
      skipping_publish_num: 5

    score_estimation:
      converged_param_type: 1
      converged_param_transform_probability: 3.0
      converged_param_nearest_voxel_transformation_likelihood: 2.3

    covariance:
      covariance_estimation:
        covariance_estimation_type: 0

    dynamic_map_loading:
      update_distance: 20.0
      map_radius: 150.0
      lidar_radius: 100.0
